#pragma once
#define HIP_SEND_DATA_HEAD1 0x7E
#define HIP_SEND_DATA_HEAD2 0xF2
#define HIP_SEND_DATA_END1  0xE1
#define HIP_SEND_DATA_END2  0xEE
#define KNEE_SEND_DATA_HEAD1 0x7C
#define KNEE_SEND_DATA_HEAD2 0xF4
#define KNEE_SEND_DATA_END1 0xE3
#define KNEE_SEND_DATA_END2 0xEC